### ISSUE TITLE
Any support for Dell XPS 9570 ?

### ISSUE THREAD

**Issue by sahlouls** [hmaarrfk/Validity91#10]
Hi,

I don't know if it is the right place to ask this question. Any support for Dell XPS 9570 fingerprint reader ?

Regards

**Comment by hmaarrfk** [comment]
not sure, it is probably a different sensor TBH

See https://github.com/hmaarrfk/Validity91/issues/5 for a similar discussion

**Comment by sahlouls** [comment]
~ -> lsusb
Bus 002 Device 002: ID 13b1:0041 Linksys
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 27c6:5395
Bus 001 Device 003: ID 0cf3:e300 Atheros Communications, Inc.
Bus 001 Device 005: ID 0c45:671d Microdia
Bus 001 Device 002: ID 25a7:fa23
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Dell XPS 9570 has another updated godfix reader: 27c6:5395

How to learn to reverse engineer this thing ?

**Comment by hmaarrfk** [comment]
you have to sniff packets from the USB. Wireshark is your friend.

**Comment by hmaarrfk** [comment]
sahlouls, thank you for reaching out, but reverse engineering the sensor on the 9570 seems to be out of scope for this project.

May I close this issue?

**Comment by berglh** [comment]
@hmaarrfk apart from sniffing the USB protocol on wireshark (it would be possible for me to do this), what else is involved with making this work. Would be great to add support, but shouldn't this be more of a linux driver support issue than for Validity 91 specifically; excuse my ignorance.

I am using a 9570 also FWIW and thinking about the usefulness of the fingerprint scanner.

**Comment by hmaarrfk** [comment]
it depends what is returned.

Does it return a match/no match

or a whole image?

This one returns a tiny image. Not good enough for the libfprint on linux..

**Comment by xerpi** [comment]
Hi, I'm a C developer with some experience with writing Linux drivers, reverse engineering and Wireshark. I also own a Dell XPS 9570 and I'd like to get the fingerprint sensor working. Maybe we could create a separate Gitter or Discord room specifically for the `27c6:5395` Goodix Fingerprint sensor to discuss about it.

**Comment by hmaarrfk** [comment]
@xerpi that is a good idea. 9570 is definitely out of scope for this project

**Comment by leoheck** [comment]
@xerpi you have a good knowledge to start this. What if you create a new repo on github for that?

**Comment by leoheck** [comment]
I also found this, https://github.com/IDerr/Goodix92/issues
But it is empty.

**Comment by xerpi** [comment]
@leoheck Unfortunately I had to pause the reverse engineering because I've started to get busy with the University. I have a quite nice IDA database (.idb) of the Windows driver DLL and I wouldn't mind sharing it.

**Comment by leoheck** [comment]
Oh, ok.

Your IDA database can be put on a google drive or similar?
Why not share online and add an issue here with the url https://github.com/IDerr/Goodix92/issues 
Maybe the guy can use it. 

I just finished my windows VM to test the reverse engineering process described here by @hmaarrfk 

Everything looks good the fingerprint sensor was recognized by the windows but the setup is not working for some reason. I am currently stuck in this screen and notthing happens.

![image](https://user-images.githubusercontent.com/1277920/47622802-21d9f480-dae8-11e8-83ca-3ab617f23d46.png)

**Comment by IDerr** [comment]
Hi everyone 
@leoheck : It will be stuck at this part, because your VM can't emulate intel SGX :( 
You have to create a VM with KVM patched for sgx : https://github.com/intel/kvm-sgx

I think that the best way to create the driver is to reverse engineer the windows driver :)
We can create a gitter or something to keep in touch if you want

**Comment by IDerr** [comment]
I have opened a gitter chat, you can find the link here : https://github.com/IDerr/Goodix92

**Comment by leoheck** [comment]
Hi @IDerr thanks for pointing me this Intel SGX patch. I will give it a try.
I couldn't find your URL to the gitter chat. Where it should be? On your Readme.md file?

**Comment by IDerr** [comment]
Yup. 

I think you can close this issue @hmaarrfk :D Thanks for the work btw

**Comment by hmaarrfk** [comment]
Thanks, I liked to it on the front page. Enjoy the traffic!

**Comment by IDerr** [comment]
Hello @xerpi is it possible to have your ida database for the driver ?

**Comment by xerpi** [comment]
@IDerr Sure, send me a mail to: xerpi.g.12@gmail.com and I'll send it back.
