### ISSUE TITLE
Can you share me part of your image packet.

### ISSUE THREAD

**Issue by iusearch** [hmaarrfk/Validity91#11]
I got a 06cb 0078 sensor. It seems like almost all packets are in the same process, just some commands are different. I got the image packet with head "00008c1f00003800......". Does it match your packet?

**Comment by hmaarrfk** [comment]
My image packet is literally the raw image file:

https://github.com/hmaarrfk/Validity91/blob/master/validity91.py#L152

shows that I just concatenate the strings, and convert it to an array.

**Comment by iusearch** [comment]
You mean a string with a "PNG" header? You packet include this PNG header?

**Comment by hmaarrfk** [comment]
Is that a PNG header? what command should I return you the result for?

**Comment by iusearch** [comment]
I just looking at the content of variable img. Is it a bitmap? I am not sure if my packet is in the correct format.

**Comment by iusearch** [comment]
And how do you discover that is a 112*112 image?

**Comment by hmaarrfk** [comment]
right, so mine is a bitmap. no special headers.

I discovered it was a 112x112 because I reshaped the data into a square ish 2D array. Then it seemed like the data wasn't aligned correctly. So i kept removing things until I had an image.

https://github.com/hmaarrfk/Validity91/blob/master/validity91.py#L137

I guess there is a 6 byte header, but I think it was something like "total image size" and "current packet size"

**Comment by iusearch** [comment]
Ok. Thank you. I will keep trying.

**Comment by hmaarrfk** [comment]
The rest of my dump is there, I just didn't want to be getting people's fingerprints sent to me then getting in trouble for it.

**Comment by iusearch** [comment]
Yep. You disable logging before collect the fingerprint. Then i don't have any packet to compare with.

**Comment by iusearch** [comment]
Could you please tell me the size of your img packet?

**Comment by hmaarrfk** [comment]
See comments here:
https://github.com/hmaarrfk/Validity91/blob/9224e476e7003179527f83b76d7e19ae2f7559ac/validity91.py#L346

There are 8 control column too. 
https://github.com/hmaarrfk/Validity91/blob/master/validity91.py#L161

So the image size is actually 112 * 120.
Sent in 3 packets, I think they were all equal length.
```
➤ 112 * 120 / 3 + 6                                                                                                                                           
4486.0
```

**Comment by iusearch** [comment]
Thank you very much. My packet is a little bit smaller and only one. I will find the correct format.

**Comment by hmaarrfk** [comment]
apparently i get 3 chunks: 4806, 4806, and 3846, the rest is as described above.

**Comment by iusearch** [comment]
Luckily, I got my clear fingerprint image now. I need to work on libfprint as well as you.

**Comment by hmaarrfk** [comment]
AWESOME!!!!
How big is your image? Basically, libfprint doesn't have new image matching algorithms.

Get on the gitter channel, there was a guy there working on some Neural Net to try and solve this.

**Comment by hmaarrfk** [comment]
Feel free to close this issue when you are happy. Glad I was able to help troubleshoot.

**Comment by iusearch** [comment]
It is 56(height) * 144(width). Quite small. You mean Validity 90 gitter?

**Comment by hmaarrfk** [comment]
The gitter for this project. Validity90 implements matching on the chip.
