### ISSUE TITLE
Dell XPS 13 9370

### ISSUE THREAD

**Issue by bag-man** [hmaarrfk/Validity91#5]
I'm trying to figure out what reader the XPS 13 9370 has, and whether it is supported by Validity 91. 

Happy to help test and diagnose if they are sharing the same reader with the 9360. 

Thanks!

**Comment by hmaarrfk** [comment]
can you paste the output of `lsusb`?

**Comment by bag-man** [comment]
Of course, at the very least we can determine if it is new hardware or not!

```
~ > lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0489:e0a2 Foxconn / Hon Hai
Bus 001 Device 002: ID 0bda:58f4 Realtek Semiconductor Corp.
Bus 001 Device 004: ID 27c6:5385
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
~ > lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 08)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.2 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #3 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Device 9d4e (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS525A PCI Express Card Reader (rev 01)
02:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
6e:00.0 Non-Volatile memory controller: Toshiba America Info Systems Device 0116
```

**Comment by hmaarrfk** [comment]
Are you sure you have a fingerprint sensor? It doesn't show up on your `lsusb`, unless it is `27c6:5385`

**Comment by bag-man** [comment]
Yeah it must be that, probably a different device than the Validity91, as it is part of the power button of the laptop.

Is there anything I can do to find out more about `27c6:5385`?

**Comment by tomhughes** [comment]
According to https://bugs.launchpad.net/ubuntu/+source/linux-hwe/+bug/1721909 that is a Goodix GF3208 so likely complete different.

**Comment by tomhughes** [comment]
Sorry, that is 27c6:5301 but 27c6:5385 will be a different Goodix model.

**Comment by bag-man** [comment]
Ah nicely found! I did find: https://certification.ubuntu.com/catalog/component/usb/4932/27c6%3A5385/

But it wasn't super clear what it actually was.

EDIT: https://www.mail-archive.com/search?l=fprint@lists.freedesktop.org&q=subject:%22Re%5C%3A+%5C%5Bfprint%5C%5D+Drivers+are+available+for+the+Goodix+GF3208+%5C%2F+Aquantia+Corp.+%5C%2827c6%5C%3A5301%5C%29%22&o=newest&f=1

Your right, it is Goodix.

**Comment by hmaarrfk** [comment]
Depending on how determined you are, you can probably try to reverse engineer the protocal while sniffing USB traffic in a windows VM.

Most USB traffic will be pretty small, so you can sort by data size to find the large data sizes and work backward from there.

If an image is returned, then you have the real hard task, of actually implementing a fingerprint detection algorithm, which takes time to work robustly. Libfprint doesn't work well with 112x112 image sensors right off the bat.

**Comment by bag-man** [comment]
Jeez okay, that sounds pretty involved, but fun! I can't do that kind of thing now, but it's a nice project to add to the list. 

Thanks for your help. Hopefully this thread comes up next time someone is curious about the 9370 finger print reader.

**Comment by sahlouls** [comment]
~ -> lsusb
Bus 002 Device 002: ID 13b1:0041 Linksys 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 27c6:5395  
Bus 001 Device 003: ID 0cf3:e300 Atheros Communications, Inc. 
Bus 001 Device 005: ID 0c45:671d Microdia 
Bus 001 Device 002: ID 25a7:fa23  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Dell XPS 9570 has another updated godfix reader: **27c6:5395**

How to learn to reverse engineer this thing ?

**Comment by leoheck** [comment]
Mine is `Bus 001 Device 003: ID 27c6:5395` on XPS 9570.

Dmesg shows this:
```
[    2.392492] usb 1-7: New USB device found, idVendor=27c6, idProduct=5395, bcdDevice= 1.00
[    2.392494] usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.392495] usb 1-7: Product: Goodix Fingerprint Device 
[    2.392496] usb 1-7: Manufacturer: HTMicroelectronics
[    2.392496] usb 1-7: SerialNumber: HTK32
```

**Comment by adnanjee** [comment]
I have found a code for Goodix fingerprint sensor. That code is mainly written for Android devices. I have tried to compile it for Ubuntu 19.04.            This code would be helpful to write a new driver.

https://github.com/adnanjee/Goodix-GF3208
