### ISSUE TITLE
Question about capturing usb traffic

### ISSUE THREAD

**Issue by abihf** [hmaarrfk/Validity91#9]
It's related to https://github.com/hmaarrfk/Validity91/issues/5

I tried to run windows 10 via virtualbox, and attach the usb to this vm. I installed the driver from dell website, and device manager show me correct device. When I tried to enroll my finger, I thought the vm send data to device, but when I place my finger, nothing happens. No data send from usb.

I dont use my current partition for running windows, I just installed unlicensed windows 10 home.

I know it's not related to validity sensor, but I hope you can share your experience reverse engineering fingerprint device.

**Comment by hmaarrfk** [comment]
Can you actually authenticate with your newly enrolled finger on windows?

Depending on the type of sensor, it may only send control signals. This Validity Device was probably super cheap and sends your information to Windows so that Windows (or the driver  installed on windows) can do the authentication. 

Better fingerprint sensors do not send the image through USB for security reasons. For example, apple claims that they do not send the raw image data to their processor, but rather than the authentication is done on the chip.

This works well for the well defined problem of checking if your finger is one of 5 registered fingers.

**Comment by abihf** [comment]
Sorry, I didn't mention that windows can't detect my finger. So I stuck in enrollment process.
If that is the case, is there any other way to debug my fingerprint sensor?

**Comment by hmaarrfk** [comment]
1. Were you able to pass the USB device to windows in VirtualBox?
2. Did you install the driver in windows?
3. Did you reboot windows?

**Comment by abihf** [comment]
1. Yes, it listed as unknown device before I installed driver
2. Yes, I downloaded & installed driver in windows.
3. I did after I installed devices.

**Comment by hmaarrfk** [comment]
Does it work now?

**Comment by abihf** [comment]
I still can not enroll my finger. And there is no error message.
I think you were right, the device doesn't send the data via usb.

**Comment by hmaarrfk** [comment]
I really doubt it doesn't send data through USB. You can try:
```
lspci
```
that lists the devices attached to the PCIe lanes.

**Comment by abihf** [comment]
lspci
```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:04.0 Signal processing controller: Intel Corporation Skylake Processor Thermal Subsystem (rev 08)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port (rev f1)
00:1c.2 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Device 9d4e (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS525A PCI Express Card Reader (rev 01)
02:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
6e:00.0 Non-Volatile memory controller: Device 1c5c:1527
```

lsusb
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0489:e0a2 Foxconn / Hon Hai 
Bus 001 Device 002: ID 0bda:58f4 Realtek Semiconductor Corp. 
Bus 001 Device 004: ID 27c6:5385  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by hmaarrfk** [comment]
I mean, this Bus 001 Device 004: ID 27c6:5385   has been [identified](https://www.the-sz.com/products/usbid/index.php?v=0x27C6) as being from a [company that makes fingerprint modules](http://www.goodix.com/investor/dqgg.html). 

You have to keep fiddling around until you actually get the device to be passed through.

Finally, you can run wireshark from within windows. Takes a little more work, and you can't get the initial boot up sequence, but maybe you can put your computer to sleep and wake up again to catch it.

**Comment by abihf** [comment]
Thanks, 
I will try it within windows.

**Comment by hmaarrfk** [comment]
@abihf I think it is safe for me to close this issue right? your sensor seems to be out of the scope of this project?

**Comment by abihf** [comment]
I'm sorry. Of course.
